// Build lib/client.js (the browser bundle) from lib/shared.js + src/client.js.
// No dependencies: the shared core is inlined with its `export` keywords
// stripped, then both are wrapped in the harness's ModuleLoader factory.
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url);
const read = (path) => readFileSync(new URL(path, root), "utf8");

const shared = read("lib/shared.js").replace(/^export (?=function |const |let |class )/gm, "");
const client = read("src/client.js");

const bundle = `// GENERATED by scripts/build.mjs from lib/shared.js + src/client.js. Edit those, then run \`node scripts/build.mjs\`.
window.__ModuleLoader__.load({
	id: "dsh-studio",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${shared}
${client}
		return module.exports;
	}
});
`;

writeFileSync(new URL("lib/client.js", root), bundle);
console.log(`lib/client.js written (${(bundle.length / 1024).toFixed(1)} KiB)`);
