// Build lib/client.js (the browser bundle) from lib/shared.js, locales/en.json
// and src/client/*.js. No dependencies: the shared core is inlined with its
// `export` keywords stripped, English is inlined as EN (other languages load
// on demand from /api/studio/locale), then everything is wrapped in the
// harness's ModuleLoader factory.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url);
const read = (path) => readFileSync(new URL(path, root), "utf8");

const shared = read("lib/shared.js").replace(/^export (?=function |const |let |class )/gm, "");
const { version } = JSON.parse(read("package.json"));
const en = JSON.stringify(JSON.parse(read("locales/en.json")), null, "\t");
const parts = readdirSync(new URL("src/client/", root))
	.filter((name) => name.endsWith(".js"))
	.sort()
	.map((name) => `//#region ${name}\n${read("src/client/" + name)}\n//#endregion ${name}`);
const client = parts.join("\n").replace("__STUDIO_VERSION__", version);

const bundle = `// GENERATED by scripts/build.mjs from lib/shared.js, locales/en.json and src/client/*.js. Edit those, then run \`node scripts/build.mjs\`.
window.__ModuleLoader__.load({
	id: "dsh-studio",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${shared}
const EN = ${en};
${client}
		return module.exports;
	}
});
`;

writeFileSync(new URL("lib/client.js", root), bundle);
console.log(`lib/client.js written (${(bundle.length / 1024).toFixed(1)} KiB, ${parts.length} client modules)`);
